import streamlit as st
import pickle
import numpy as np

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="California Housing Price Predictor",
    page_icon="🏠",
    layout="wide"
)

# -----------------------------
# Background Image + Text Styling
# -----------------------------
page_bg = """
<style>

/* Background Image */
[data-testid="stAppViewContainer"]{
background-image: url("https://images.unsplash.com/photo-1560518883-ce09059eeffa");
background-size: cover;
background-position: center;
}

/* Transparent Header */
[data-testid="stHeader"]{
background: rgba(0,0,0,0);
}

/* Dark Bold Text */
h1, h2, h3, h4, h5, h6, p, label {
color: #111111 !important;
font-weight: 700 !important;
}

/* Sidebar Styling */
[data-testid="stSidebar"]{
background-color: rgba(255,255,255,0.85);
color: black;
font-weight: bold;
}

/* Button Styling */
.stButton>button {
background-color: #0f4c81;
color: white;
font-weight: bold;
border-radius: 8px;
padding: 10px 20px;
}

</style>
"""

st.markdown(page_bg, unsafe_allow_html=True)

# -----------------------------
# Load Model
# -----------------------------
with open("california_housing.pkl", "rb") as file:
    model = pickle.load(file)

# -----------------------------
# Sidebar
# -----------------------------
with st.sidebar:

    st.title("👩‍💻 Developer Info")

    st.write("**Name:** Sakshi Patil")
    st.write("**Field:** Machine Learning / Data Science")

    st.markdown("---")

    st.subheader("📬 Contact")

    st.write("📧 Email: sakshi@email.com")
    st.write("🔗 LinkedIn: linkedin.com/in/sakshi")
    st.write("💻 GitHub: github.com/sakshi")

    st.markdown("---")

    st.info("This ML model predicts California housing prices using housing statistics.")

# -----------------------------
# Main Title
# -----------------------------
st.title("🏠 California Housing Price Prediction System")

st.write(
"""
Provide housing details below to estimate the **expected house price**.
Make sure the values follow the measurement units mentioned.
"""
)

# -----------------------------
# Input Section
# -----------------------------
col1, col2 = st.columns(2)

with col1:

    MedInc = st.number_input(
        "Median Income (in $10,000 units)",
        min_value=0.0,
        help="Example: Enter 5 if median income is $50,000"
    )

    HouseAge = st.number_input(
        "House Age (Years)",
        min_value=0.0
    )

    AveRooms = st.number_input(
        "Average Number of Rooms",
        min_value=0.0
    )

    AveBedrms = st.number_input(
        "Average Number of Bedrooms",
        min_value=0.0
    )

with col2:

    Population = st.number_input(
        "Population in the Area",
        min_value=0.0
    )

    AveOccup = st.number_input(
        "Average Occupancy (People per House)",
        min_value=0.0
    )

    Latitude = st.number_input(
        "Latitude (Location Coordinate)"
    )

    Longitude = st.number_input(
        "Longitude (Location Coordinate)"
    )

# -----------------------------
# Prediction Button
# -----------------------------
st.markdown("###")

if st.button("🔍 Predict House Price"):

    features = np.array([[MedInc, HouseAge, AveRooms, AveBedrms,
                          Population, AveOccup, Latitude, Longitude]])

    prediction = model.predict(features)

    predicted_price = prediction[0] * 100000

    # Dark styled result box
    st.markdown(
        f"""
        <div style="
        background-color: rgba(255,255,255,0.9);
        padding:25px;
        border-radius:10px;
        text-align:center;
        font-size:26px;
        font-weight:bold;
        color:#111111;">
        🏡 Estimated House Price: ${predicted_price:,.2f} USD
        </div>
        """,
        unsafe_allow_html=True
    )

    # Note text
    st.markdown(
        """
        <div style="
        margin-top:15px;
        font-size:18px;
        font-weight:bold;
        color:#222222;">
        Note: This value is an estimated prediction generated by the Machine Learning model.
        </div>
        """,
        unsafe_allow_html=True
    )
