import streamlit as st
import pickle
import numpy as np

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="California Housing Price Predictor",
    page_icon="🏠",
    layout="wide"
)

# -----------------------------
# Background Image with Transparency
# -----------------------------
page_bg = """
<style>
[data-testid="stAppViewContainer"]{
background-image: url("https://images.unsplash.com/photo-1560518883-ce09059eeffa");
background-size: cover;
background-position: center;
}

[data-testid="stHeader"]{
background: rgba(0,0,0,0);
}

[data-testid="stToolbar"]{
right: 2rem;
}

.main{
background-color: rgba(255,255,255,0.7);
padding: 2rem;
border-radius: 10px;
}
</style>
"""

st.markdown(page_bg, unsafe_allow_html=True)

# -----------------------------
# Load Model
# -----------------------------
with open("california_housing.pkl", "rb") as file:
    model = pickle.load(file)

# -----------------------------
# Sidebar (Left Panel)
# -----------------------------
with st.sidebar:
    
    st.title("👩‍💻 Developer Info")
    
    st.write("**Name:** Sakshi Patil")
    st.write("**Field:** Data Science / Machine Learning")
    
    st.markdown("---")
    
    st.subheader("📬 Contact")
    
    st.write("📧 Email: sakshi@email.com")
    st.write("🔗 LinkedIn: linkedin.com/in/sakshi")
    st.write("💻 GitHub: github.com/sakshi")
    
    st.markdown("---")
    
    st.info("This ML model predicts California house prices based on housing statistics.")

# -----------------------------
# Main Title
# -----------------------------
st.title("🏠 California Housing Price Prediction System")

st.write(
"""
Provide the housing details below to estimate the **expected house price**.
All values should be entered carefully using the measurement units mentioned.
"""
)

# -----------------------------
# Input Section
# -----------------------------

col1, col2 = st.columns(2)

with col1:

    MedInc = st.number_input(
        "Median Income (in $10,000 units)",
        min_value=0.0,
        help="Example: Enter 5 if the median income is $50,000"
    )

    HouseAge = st.number_input(
        "House Age (Years)",
        min_value=0.0
    )

    AveRooms = st.number_input(
        "Average Number of Rooms",
        min_value=0.0
    )

    AveBedrms = st.number_input(
        "Average Number of Bedrooms",
        min_value=0.0
    )

with col2:

    Population = st.number_input(
        "Population in the Area",
        min_value=0.0
    )

    AveOccup = st.number_input(
        "Average Occupancy (People per House)",
        min_value=0.0
    )

    Latitude = st.number_input(
        "Latitude (Location Coordinate)"
    )

    Longitude = st.number_input(
        "Longitude (Location Coordinate)"
    )

# -----------------------------
# Prediction Button
# -----------------------------
st.markdown("###")

if st.button("🔍 Predict House Price"):

    features = np.array([[MedInc, HouseAge, AveRooms, AveBedrms,
                          Population, AveOccup, Latitude, Longitude]])

    prediction = model.predict(features)

    predicted_price = prediction[0] * 100000  # converting to dollars

    st.success(f"🏡 Estimated House Price: **${predicted_price:,.2f} USD**")

    st.info("Note: This is an estimated value generated by the Machine Learning model.")
